// Phase 0.2 — index the harvested image pool so later phases can PICK from it.
// Run:  node scripts/catalogue-assets.mjs
// Writes: revamp-handoff/asset-catalogue.md
//
// WHY A CATALOGUE AND NOT A BULK CONVERSION (deviation from 0.2 as written):
//
// 0.2 says "convert to AVIF/WebP, organize public/images/{venues,partners,
// people,brand}/". The architecture that actually emerged does better than that
// and makes the bulk step wrong:
//
//   • Images are imported statically from `src/assets/images/**`, which gives
//     next/image automatic AVIF+WebP negotiation, a blur placeholder, intrinsic
//     dimensions (no CLS) and content-hashed filenames. Files dropped in
//     `public/` get none of that — they are served raw and byte-for-byte.
//   • Format conversion therefore belongs at the point of use. It already
//     happens: `prep-home-assets.mjs`, `prep-hero-assets.mjs` and
//     `prep-video-thumbs.mjs` each emit `.webp` for the picks that phase needs.
//   • Bulk-converting all 116 unique originals now would add megabytes to the
//     repo for images no page imports, and DESIGN.md's whole method is
//     art-directed selection ("one big confident image per section"), not a
//     dumping ground.
//
// So: this script does the part that is genuinely useful up front — tell us
// what we have, at what size, what is a duplicate, and what is already spoken
// for — and each phase keeps writing its own small prep script.
import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import { stat } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

const SRC = "assets-raw/wegood4u";
const OUT = "revamp-handoff/asset-catalogue.md";

/** WordPress emits a `-scaled` 2560px variant beside the original upload. */
const scaledTwin = (name) => name.replace(/-scaled(\.\w+)$/, "$1");
const isScaled = (name) => /-scaled\.\w+$/.test(name);

/** Bucket from the filename. Conservative: anything unrecognised lands in
 *  `unsorted` for a human to look at rather than being confidently mis-filed.
 *
 *  The `2025_03_*` snake_case batch is the big one — ~40 named partner venues
 *  (kiti_panit, khagee, beast_burger, hannah…). Those are the raw material for
 *  `/our-partners` and `/venue/[slug]` in Phases 4–5, and they were sitting in
 *  `unsorted` until this rule existed. */
function bucket(name) {
  const n = name.toLowerCase();
  if (/wegood4u|thaigood|msiagood|logo|cropped/.test(n)) return "brand";
  if (/issen|patus|magokoro|foong|tiger-kingdom|sunsan/.test(n)) return "venues-wp";
  if (/sticker|line_album/.test(n)) return "stickers";
  if (/hero|business/.test(n)) return "editorial";
  if (/^\d{4}_\d{2}_image-/.test(n)) return "editorial";
  if (/^\d{4}_\d{2}_(\d{8}_\d{6}|img_)/.test(n)) return "shoot";
  // Elementor's own generated crops — derivatives of originals we already have,
  // hash-suffixed and arbitrarily sized. Never pick from these.
  if (/^elementor_thumbs_/.test(n)) return "elementor-derivatives";
  // The 2025_03 batch is named partner venues: snake_case, hyphenated, or Thai
  // script (`ใต้ถุนบ้าน`). `the-baristo` and `hannah` also appear in the app's
  // own "Recommended" rows, which is a good sign these are the live partners.
  if (/^\d{4}_\d{2}_[^\d].*\.\w+$/.test(n)) return "partners";
  return "unsorted";
}

async function usedPicks() {
  const files = (await readdir("scripts")).filter((f) => f.startsWith("prep-"));
  const picks = new Set();
  for (const f of files) {
    const body = await readFile(path.join("scripts", f), "utf8");
    for (const m of body.matchAll(/["'`]([0-9]{4}_[0-9]{2}_[^"'`]+?\.(?:jpg|jpeg|png|webp))["'`]/g)) {
      picks.add(m[1]);
    }
  }
  return picks;
}

const names = (await readdir(SRC)).filter((f) => !f.startsWith("."));
const used = await usedPicks();

const rows = [];
for (const name of names) {
  const full = path.join(SRC, name);
  const [{ size }, meta] = await Promise.all([
    stat(full),
    sharp(full).metadata().catch(() => ({})),
  ]);
  rows.push({
    name,
    bucket: bucket(name),
    w: meta.width ?? 0,
    h: meta.height ?? 0,
    kb: Math.round(size / 1024),
    scaled: isScaled(name),
    twin: isScaled(name) && names.includes(scaledTwin(name)),
    used: used.has(name),
  });
}

rows.sort((a, b) => a.bucket.localeCompare(b.bucket) || a.name.localeCompare(b.name));

const byBucket = rows.reduce((acc, r) => ((acc[r.bucket] ??= []).push(r), acc), {});
const dupes = rows.filter((r) => r.twin);
const unusedCount = rows.filter((r) => !r.used && !r.twin).length;

const lines = [
  "# Harvested image catalogue",
  "",
  "> Generated by `node scripts/catalogue-assets.mjs`. Do not hand-edit.",
  "> Source pool: `assets-raw/wegood4u` (gitignored, 147MB, 132 files).",
  "",
  "**Pick from this list, then write a small `scripts/prep-<phase>-assets.mjs`**",
  "that crops and emits `.webp` into `src/assets/images/<area>/`. Do not copy",
  "originals into `public/` — static imports are what give us AVIF/WebP",
  "negotiation, blur placeholders and no CLS.",
  "",
  `- Files: **${rows.length}**`,
  `- WordPress \`-scaled\` duplicates: **${dupes.length}** (prefer the non-scaled original)`,
  `- Already used by a prep script: **${rows.filter((r) => r.used).length}**`,
  `- Unused and unique — available to later phases: **${unusedCount}**`,
  "",
  "⚠ Many `2024_11` / `2024_12` / `2025_01` frames are video stills with a",
  "BURNT-IN watermark top-right. Crop it out — see `prep-home-assets.mjs`.",
  "",
];

for (const [name, list] of Object.entries(byBucket)) {
  lines.push(`## ${name} (${list.length})`, "");
  lines.push("| file | dimensions | size | status |", "|---|---|---|---|");
  for (const r of list) {
    const status = r.twin ? "duplicate of non-scaled" : r.used ? "**in use**" : "available";
    lines.push(`| \`${r.name}\` | ${r.w}×${r.h} | ${r.kb} KB | ${status} |`);
  }
  lines.push("");
}

await mkdir(path.dirname(OUT), { recursive: true });
await writeFile(OUT, lines.join("\n"));

console.log(`Catalogued ${rows.length} files → ${OUT}`);
console.log(`  duplicates: ${dupes.length}   in use: ${rows.filter((r) => r.used).length}   available: ${unusedCount}`);
for (const [b, l] of Object.entries(byBucket)) console.log(`  ${b}: ${l.length}`);
